// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Info: typeof import('./components/Info.vue')['default']
    Portfolio: typeof import('./components/Portfolio.vue')['default']
  }
}

export { }
